export const SAVE_QUESTION_ALL_DATA = 'SAVE_QUESTION_ALL_DATA';
export const SAVE_QUESTION_DATA = 'SAVE_QUESTION_DATA';
export const SAVE_QUESTION_LOADING = 'SAVE_QUESTION_LOADING';
export const SAVE_ANSWERS_DATA = 'SAVE_ANSWERS_DATA';
export const RESET_ANSWER_DATA = 'RESET_ANSWER_DATA';

export const SAVE_ANSWER_DATA = 'SAVE_ANSWER_DATA';
export const SAVE_ANSWER_MASS_DATA = 'SAVE_ANSWER_MASS_DATA';
export const SAVE_QUESTION_PAST_DATA = 'SAVE_QUESTION_PAST_DATA';
export const SAVE_ANSWERS_NOT_SEND_DATA = 'SAVE_ANSWERS_NOT_SEND_DATA';
export const SAVE_ANSWERS_SEND_DATA = 'SAVE_ANSWERS_SEND_DATA';
export const SAVE_ANSWERS_NOT_SEND_ALL_DATA = 'SAVE_ANSWERS_NOT_SEND_ALL_DATA';
export const SAVE_ANSWERS_SEND_ALL_DATA = 'SAVE_ANSWERS_SEND_ALL_DATA';

//Question/folder
export const SAVE_QUESTION_FOLDER_DATA = 'SAVE_QUESTION_FOLDER_DATA';
export const SAVE_QUESTION_FOLDER_LOADING = 'SAVE_QUESTION_FOLDER_LOADING';

//auth
export const SAVE_AUTH_TOKEN = 'SAVE_AUTH_TOKEN';
export const SAVE_AUTH_USER_DATA = 'SAVE_AUTH_USER_DATA';
export const DELETE_AUTH_USER_DATA = 'DELETE_AUTH_USER_DATA';
